version: '3.9'

services:
  zimasocial-backend:
    image: zimasocial:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zimasocialcontainer
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/zimasocial
    ports:
      - "8081:8081"
    networks:
      - zimanetwork
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: zimaadmin
      POSTGRES_DB: zimasocial
    networks:
      - zimanetwork
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

networks:
  zimanetwork:
    driver: bridge

