package com.zima.zimasocial.entity;

public enum NotificationType {
    POST_LIKED,
    COMMENT_LIKED,
    USER_FOLLOWED_YOU,
    USER_SENT_FOLLOW_REQUEST,
    USER_FOLLOW_REQUEST_ACCEPTED,
    POST_COMMENTED,
    COMMENT_REPLIED,
    POST_DELETED,
    POST_SHARED,
    WELCOME,
    NEWS,
    IMPORTANT,
    VERY_IMPORTANT,
    DANGER,
    NEW_MESSAGE
}
