spring:
  application:
    name: zimasocial
  datasource:
    url: jdbc:postgresql://localhost:5432/zimasocial
    username: zimaadmin
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: https://accounts.google.com
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            scope:
              - email
              - profile
              - openid
        client:
          registration:
            google:
              client-id: 460270477882-v8qn6d75bgnbash0v7fum69pca94ftdj.apps.googleusercontent.com
              client-secret: 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
              scope: openid,profile,email
  flyway:
    locations: classpath:db/migrations
    enabled: false
    baseline-on-migrate: true
    default-schema: zimasocial
server:
  port: 8081

jwt:
  secret: NkYyNjE5N0UzNEIzMzgyNUY1OTQ2QUZGNkE0NTJFN0U=