--
-- PostgreSQL database dump
-- For Zima Social Platform
--

-- Initial Setup
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;

--
-- Core User Tables
--

-- Users table
CREATE TABLE public.users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255),
    name character varying(255),
    family_name character varying(255),
    auth_provider character varying(255),
    avatar_url character varying(255),
    bio character varying(255),
    slug character varying(255),
    is_private boolean,
    followers_count integer,
    following_count integer,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk82kvqupf9ax45leg8b0nofwh2 UNIQUE (slug)
);

-- User roles table
CREATE TABLE public.user_role (
    user_id bigint NOT NULL,
    role character varying(255),
    CONSTRAINT user_role_role_check CHECK (
        (role)::text = ANY ((ARRAY['regular', 'editor', 'admin', 'superadmin'])::text[])
    )
);

--
-- Content Tables
--

-- Posts table
CREATE TABLE public.post (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint,
    content character varying(255),
    url character varying(255),
    type character varying(255),
    like_count integer,
    comment_count integer,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT post_pkey PRIMARY KEY (id),
    CONSTRAINT post_type_check CHECK (
        (type)::text = ANY ((ARRAY['music', 'movie', 'book', 'any'])::text[])
    )
);

-- Comments table
CREATE TABLE public.comment (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint,
    post_id bigint,
    parent_id bigint,
    content character varying(255),
    like_count integer,
    comment_count integer,
    reply_count integer,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT comment_pkey PRIMARY KEY (id)
);

-- Likes table
CREATE TABLE public.likes (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint,
    post_id bigint,
    comment_id bigint,
    created_at timestamp(6) without time zone,
    CONSTRAINT likes_pkey PRIMARY KEY (id)
);

--
-- Foreign Key Constraints
--

-- User role constraints
ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fkj345gk1bovqvfame88rcx7yyx
    FOREIGN KEY (user_id) REFERENCES public.users(id);

-- Post constraints
ALTER TABLE ONLY public.post
    ADD CONSTRAINT fk7ky67sgi7k0ayf22652f7763r
    FOREIGN KEY (user_id) REFERENCES public.users(id);

-- Comment constraints
ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fkde3rfu96lep00br5ov0mdieyt
    FOREIGN KEY (parent_id) REFERENCES public.comment(id);

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fkqm52p1v3o13hy268he0wcngr5
    FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fks1slvnkuemjsq2kj4h3vhx7i1
    FOREIGN KEY (post_id) REFERENCES public.post(id);

-- Likes constraints
ALTER TABLE ONLY public.likes
    ADD CONSTRAINT fk8arpx7i3g3e5dammtdsira2m6
    FOREIGN KEY (comment_id) REFERENCES public.comment(id);

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT fknvx9seeqqyy71bij291pwiwrg
    FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.likes
    ADD CONSTRAINT fkowd6f4s7x9f3w50pvlo6x3b41
    FOREIGN KEY (post_id) REFERENCES public.post(id);