-- NOTIFICATION TABLE
CREATE TABLE public.notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    content VARCHAR(512),
    url TEXT,
    receiver_user_id BIGINT NOT NULL,
    type VARCHAR(64),
    sender_user_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_created_at TIMESTAMP
);

-- CHECK NOTIFICATION TYPE
ALTER TABLE public.notification
ADD CONSTRAINT check_notification_type
CHECK(type IN ('post_liked', 'comment_liked',
               'user_followed_you', 'post_commented',
               'comment_liked', 'comment_replied',
               'post_deleted', 'post_shared',
               'welcome', 'news', 'important',
               'very_important','danger'));

-- Notification - Receiver User Foreign Key
ALTER TABLE public.notification
ADD CONSTRAINT fk_notification_receiver_user_id
FOREIGN KEY (receiver_user_id) REFERENCES public.users(id);

-- Notification - Sender User Foreign Key
ALTER TABLE public.notification
ADD CONSTRAINT fk_notification_sender_user_id
FOREIGN KEY (sender_user_id) REFERENCES public.users(id);



