ALTER TABLE comment
ADD COLUMN IS_DELETED BOOLEAN DEFAULT false;
ALTER TABLE post
ADD COLUMN IS_DELETED BOOLEAN DEFAULT false;
ALTER TABLE likes
ADD COLUMN IS_DELETED BOOLEAN DEFAULT false;
ALTER TABLE follower
ADD COLUMN IS_DELETED BOOLEAN DEFAULT false;
ALTER TABLE users
ADD COLUMN IS_DELETED BOOLEAN DEFAULT false;
ALTER TABLE refresh_token
ADD COLUMN IS_DELETED BOOLEAN DEFAULT false;
ALTER TABLE user_role
ADD COLUMN IS_DELETED BOOLEAN DEFAULT false;
ALTER TABLE notification
ADD COLUMN IS_DELETED BOOLEAN DEFAULT false;
