CREATE TABLE REPORT_REASON (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64),
    CONSTRAINT id_report_reason_primary_key PRIMARY KEY (id)
);

INSERT INTO report_reason (name) VALUES ('spam'), ('offensive'), ('bad_language');

ALTER TABLE public.post_report
ADD COLUMN report_reason_id BIGINT NOT NULL;

ALTER TABLE public.post_report
ADD CONSTRAINT fk_post_report_reason
FOREIGN KEY (report_reason_id) REFERENCES public.report_reason(id);

ALTER TABLE public.post_report
ADD COLUMN report_type VARCHAR(64) NOT NULL;
