CREATE TABLE user_relations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    initiater_id BIGINT,
    receiver_id BIGINT,
    relation VARCHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_initiater_user FOREIGN KEY (initiater_id) REFERENCES public.users(id),
    CONSTRAINT fk_receiver_user FOREIGN KEY (receiver_id) REFERENCES public.users(id)
);