CREATE TABLE user_mobile_token (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
      user_id BIGINT REFERENCES public.users(id),
      device_token TEXT NOT NULL,
      is_valid BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP,
      is_deleted BOOLEAN DEFAULT false,
      CONSTRAINT id_user_mobile_token_primary_key PRIMARY KEY (id)
);