--- CREATE USER IMAGE TABLE
CREATE TABLE files (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     user_id BIGINT,
     name TEXT,
     media_type VARCHAR(64) NOT NULL,
     data BYTEA,
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP,
     is_deleted BOOLEAN DEFAULT false
);





