CREATE TABLE TODAYS_POST (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    todays_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    is_deleted BOOLEAN DEFAULT false,
    CONSTRAINT pk_todays_post PRIMARY KEY (id)
);

ALTER TABLE TODAYS_POST
ADD CONSTRAINT fk_todays_post_post
FOREIGN KEY (post_id) REFERENCES public.post(id);

ALTER TABLE TODAYS_POST
ADD CONSTRAINT fk_todays_post_author
FOREIGN KEY (author_id) REFERENCES public.users(id);