ALTER TABLE comment
ALTER COLUMN created_at
SET DATA TYPE TIMESTAMP WITH TIME ZONE
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE chat_message
ALTER COLUMN created_at
SET DATA TYPE TIMESTAMP WITH TIME ZONE
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE follow_request
ALTER COLUMN created_at
SET DATA TYPE TIMESTAMP WITH TIME ZONE
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE notification
ALTER COLUMN created_at
SET DATA TYPE TIMESTAMP WITH TIME ZONE
USING created_at AT TIME ZONE 'UTC';
