ALTER TABLE refresh_token
ALTER COLUMN expires_at
SET DATA TYPE TIMESTAMP WITH TIME ZONE
USING expires_at AT TIME ZONE 'UTC';

ALTER TABLE refresh_token
ALTER COLUMN created_at
SET DATA TYPE TIMESTAMP WITH TIME ZONE
USING created_at AT TIME ZONE 'UTC';
