-- CUSTOM DOMAIN
CREATE DOMAIN email_address AS VARCHAR(255)
    CHECK (VALUE ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$');

-- USERS TABLE
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email email_address,
    slug VARCHAR(64),
    name VARCHAR(64),
    family_name VARCHAR(64),
    is_private BOOLEAN DEFAULT false,
    bio VARCHAR(255),
    followers_count INT DEFAULT 0,
    following_count INT DEFAULT 0,
    avatar_url VARCHAR(512),
    auth_provider VARCHAR(32),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    is_deleted BOOLEAN DEFAULT false,
    CONSTRAINT id_users_primary_key PRIMARY KEY (id),
    CONSTRAINT unique_slug UNIQUE (slug)
);

-- USER ROLE TABLE
CREATE TABLE public.user_role (
    user_id BIGINT,
    role VARCHAR(64) NOT NULL,
    is_deleted BOOLEAN DEFAULT false,
    PRIMARY KEY (user_id, role),
    CONSTRAINT fk_user_user_role FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- POST TABLE
CREATE TABLE public.post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    like_count INT DEFAULT 0,
    comment_count INT DEFAULT 0,
    type VARCHAR(64) DEFAULT 'any',
    content TEXT,
    url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    is_deleted BOOLEAN DEFAULT false,
    CONSTRAINT id_post_primary_key PRIMARY KEY (id),
    CONSTRAINT check_post_type CHECK (type IN ('any', 'music', 'movie', 'book')),
    CONSTRAINT fk_post_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- COMMENT TABLE
CREATE TABLE public.comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    parent_id BIGINT,
    content VARCHAR(255) NOT NULL CHECK (length(trim(content)) > 0),
    like_count INT DEFAULT 0,
    reply_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    is_deleted BOOLEAN DEFAULT false,
    CONSTRAINT id_comment_primary_key PRIMARY KEY (id),
    CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES public.users(id),
    CONSTRAINT fk_comment_post FOREIGN KEY (post_id) REFERENCES public.post(id),
    CONSTRAINT fk_parent_comment FOREIGN KEY (parent_id) REFERENCES public.comment(id)
);

-- LIKES TABLE
CREATE TABLE public.likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    post_id BIGINT,
    comment_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT false,
    CONSTRAINT id_likes_primary_key PRIMARY KEY (id),
    CONSTRAINT check_post_and_like CHECK (
        (post_id IS NULL AND comment_id IS NOT NULL)
        OR (post_id IS NOT NULL AND comment_id IS NULL)
    ),
    CONSTRAINT fk_like_user FOREIGN KEY (user_id) REFERENCES public.users(id),
    CONSTRAINT fk_like_post FOREIGN KEY (post_id) REFERENCES public.post(id),
    CONSTRAINT fk_like_comment FOREIGN KEY (comment_id) REFERENCES public.comment(id)
);

-- FOLLOWER TABLE
CREATE TABLE public.follower (
    follower_id BIGINT NOT NULL,
    following_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT false,
    CONSTRAINT fk_follower_follower FOREIGN KEY (follower_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT fk_follower_following FOREIGN KEY (following_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT prevent_self_follow CHECK (follower_id != following_id)
);

-- REFRESH TOKEN TABLE
CREATE TABLE public.refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    token_hash TEXT,
    revoked BOOLEAN DEFAULT FALSE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    device_info VARCHAR(255),
    ip_address VARCHAR(64),
    is_deleted BOOLEAN DEFAULT false,
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- NOTIFICATION TABLE
CREATE TABLE public.notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    content VARCHAR(512),
    url TEXT,
    receiver_user_id BIGINT NOT NULL,
    type VARCHAR(64) NOT NULL,
    sender_user_id BIGINT,
    target_collection VARCHAR(64),
    target_id BIGINT,
    post_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    is_deleted BOOLEAN DEFAULT false,
    CONSTRAINT fk_notification_receiver_user_id FOREIGN KEY (receiver_user_id) REFERENCES public.users(id),
    CONSTRAINT fk_notification_sender_user_id FOREIGN KEY (sender_user_id) REFERENCES public.users(id),
    CONSTRAINT fk_notification_post FOREIGN KEY (post_id) REFERENCES public.post(id)
);

-- REPORT_REASON TABLE
CREATE TABLE public.report_reason (
    name VARCHAR(64),
    CONSTRAINT id_report_name_key PRIMARY KEY (name)
);

-- POST_REPORT TABLE
CREATE TABLE public.post_report (
    reporter_id BIGINT NOT NULL,
    reported_post_id BIGINT NOT NULL,
    reported_post_owner_id BIGINT NOT NULL,
    report_reason VARCHAR(64) NOT NULL,
    PRIMARY KEY (reporter_id, reported_post_id),
    CONSTRAINT fk_reporter_user FOREIGN KEY (reporter_id) REFERENCES public.users(id),
    CONSTRAINT fk_reported_post FOREIGN KEY (reported_post_id) REFERENCES public.post(id),
    CONSTRAINT fk_reported_user FOREIGN KEY (reported_post_owner_id) REFERENCES public.users(id),
    CONSTRAINT fk_post_report_reason FOREIGN KEY (report_reason) REFERENCES public.report_reason(name)
);

-- SEED REPORT REASONS
INSERT INTO public.report_reason (name)
VALUES ('spam'), ('offensive'), ('bad_language');
