ALTER TABLE comment
ALTER COLUMN updated_at
SET DATA TYPE TIMESTAMP WITH TIME ZONE
USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE chat_message
ALTER COLUMN updated_at
SET DATA TYPE TIMESTAMP WITH TIME ZONE
USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE follow_request
ALTER COLUMN updated_at
SET DATA TYPE TIMESTAMP WITH TIME ZONE
USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE notification
ALTER COLUMN updated_at
SET DATA TYPE TIMESTAMP WITH TIME ZONE
USING updated_at AT TIME ZONE 'UTC';
